# Generated by Django 3.0.2 on 2020-01-05 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en la cual el objeto fue ultimamente modificado', verbose_name='modified at')),
                ('is_admin', models.BooleanField(default=False, help_text='Los administradores de los círculos pueden actualizar los datos de los círculos y administrar sus miembros', verbose_name='Administrador de Circulo')),
                ('used_invitations', models.PositiveSmallIntegerField(default=0, verbose_name='invitaciones usadas')),
                ('remaining_invitations', models.PositiveSmallIntegerField(default=0, verbose_name='invitaciones sobrantes')),
                ('rides_taken', models.PositiveIntegerField(default=0, verbose_name='Viajes tomados')),
                ('rides_offered', models.PositiveIntegerField(default=0, verbose_name='Viajes ofrecidos')),
                ('is_active', models.BooleanField(default=True, help_text='solo los usuarios activos pueden interactuar en los círculos', verbose_name='Estado de activo')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.Circle')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(through='circles.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
