# Generated by Django 3.0.2 on 2020-01-25 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en la cual el objeto fue ultimamente modificado', verbose_name='modified at')),
                ('comments', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=1)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.Circle')),
                ('rated_user', models.ForeignKey(help_text='Usuario que recibe la calificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_calificado', to=settings.AUTH_USER_MODEL)),
                ('rating_user', models.ForeignKey(help_text='Usuarios que emiten la calificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificacion_usuario', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paseo_calificado', to='rides.Ride')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
